apiVersion: v1
kind: ServiceMonitor
metadata:
  name: kubelet-cadvisor
  namespace: kube-system
spec:
  endpoints:
  - port: https-metrics
    path: /metrics/cadvisor
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabelings:
    - sourceLabels: [__metrics_path__]
      targetLabel: metrics_path
  selector:
    matchLabels:
      k8s-app: kubelet
