---
- name: Install Zabbix active agent
  hosts: master
  become: yes

  vars:
    # Environment-style parameters
    zabbix_env:
      server: "zabbix.example.com"
      server_active: "zabbix.example.com"
      hostname: "{{ inventory_hostname }}"
      repo_url: "https://repo.zabbix.com/zabbix/7.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-7.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm"
      agent_conf: "/etc/zabbix/zabbix_agentd.conf"

  tasks:
    - name: Install Zabbix repo
      yum:
        name: "{{ zabbix_env.repo_url }}"
        state: present

    - name: Install Zabbix agent
      yum:
        name: zabbix-agent2
        state: present

    - name: Configure Zabbix agent
      lineinfile:
        path: "{{ zabbix_env.agent_conf }}"
        regexp: "^{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
      loop:
        - { key: "Server", value: "{{ zabbix_env.server }}" }
        - { key: "ServerActive", value: "{{ zabbix_env.server_active }}" }
        - { key: "Hostname", value: "{{ zabbix_env.hostname }}" }

    - name: Enable and start Zabbix agent
      systemd:
        name: zabbix-agent2
        enabled: yes
        state: started

