# prometheus-values.yaml
prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    externalUrl: https://ocloud-bmwlab.duckdns.org/prometheus
    routePrefix: /
    retention: "15d"
    resources:
      requests:
        memory: "2Gi"
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi


server:
  extraArgs:
    web.external-url: https://ocloud-bmwlab.duckdns.org/prometheus
    web.route-prefix: /
  service:
    type: ClusterIP
    servicePort: 80
alertmanager:
  enabled: false

pushgateway:
  enabled: false

kube-state-metrics:
  enabled: true

prometheus-node-exporter:
  enabled: true

grafana:
  adminPassword: "admin"
  grafana.ini:
    server:
      root_url: https://ocloud-bmwlab.duckdns.org/grafana
      serve_from_sub_path: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: ""  # Uses default storage class
    accessModes:
      - ReadWriteOnce
    size: 10Gi

