apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: linuxptp
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: linuxptp
  template:
    metadata:
      labels:
        app: linuxptp
    spec:
      hostNetwork: true
      hostPID: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists
      containers:
      - name: ptp4l
        image: bmw.ece.ntust.edu.tw/infidel/ptp-agent:latest
        command: ["/ptp4l.sh"]
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: shared
          mountPath: /tmp
          
      - name: phc2sys
        image: bmw.ece.ntust.edu.tw/infidel/ptp-agent:latest
        command: ["/phc2sys.sh"]
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
        - name: shared
          mountPath: /tmp
          
      volumes:
      - name: config
        configMap:
          name: ptp-config
      - name: shared
        emptyDir: {}
