cni:
  exclusive: false
sctp:
  enabled: true
prometheus:
  enabled: true
  port: 9962
  serviceMonitor:
    enabled: true
    labels:
      release: prometheus
    interval: 30s

# Enable Hubble metrics (network observability)
hubble:
  enabled: true
  ui:
    enabled: true
  metrics:
    enabled:
      - dns:query;ignoreAAAA
      - drop
      - tcp
      - flow
      - icmp
      - http
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
      interval: 30s
  relay:
    enabled: true
    # tls:
    #   server:
    #     enabled: false
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus

# Enable Cilium Operator metrics
operator:
  prometheus:
    enabled: true
    port: 9963
    serviceMonitor:
      enabled: true
      labels:
        release: prometheus
      interval: 30s
