cni:
  exclusive: false
sctp:
  enabled: true

hubble:
  enabled: true
  ui:
    enabled: true
  relay:
    enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true

  metrics:
    serviceMonitor:
      enabled: true

    enableOpenMetrics: true
    enabled:
      - dns
      - drop
      - tcp
      - flows-to-world
      - port-distribution
      - icmp
      - "flow:sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"
      - "httpV2:exemplars=true;labelsContext=source_ip,source_namespace,source_workload,destination_ip,destination_namespace,destination_workload,traffic_direction;sourceContext=workload-name|reserved-identity;destinationContext=workload-name|reserved-identity"

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true

operator:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
