apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: retina
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: retina
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: metrics
    interval: 30s
